import React from "react";
import Login from "./Login/Login";

export const metadata = {
  title: "Login - Fashion",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Login />
    </>
  );
};

export default page;
