import React from "react";
import Register from "./Register/Register";

export const metadata = {
  title: "Register - Fashion",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Register />
    </>
  );
};

export default page;
