import React from "react";
import ProductDetails from "../ProductDetails/ProductDetails";

export const metadata = {
  title: "Product Details - Fashion",
  description: "Generated by create next app",
};

const page = ({ params }) => {
  const id = params.id;

  return (
    <>
      <ProductDetails id={id} />
    </>
  );
};

export default page;
